### ISSUE TITLE
Error when using Patchwork with PHP internal functions

### ISSUE THREAD

**Issue by gedex** [sirbrillig/spies#13]
### Steps to reproduce

For example I've `func.php` (of course `A` is bad function, and we want to redefine `trigger_error` with Patchwork):

```php
<?php

function A() {
	trigger_error( 'boom' );
	return false;
}
```

and here's a simple test case for that:

```php
<?php

use PHPUnit\Framework\TestCase;

class FuncTest extends TestCase {

	public function test_A() {
		\Spies\mock_function( 'trigger_error' )->and_return( null );
		$this->assertFalse( A() );
	}
}
```

and here's the error I got:

```
There was 1 error:

1) FuncTest::test_A
boom

./vendor/antecedent/patchwork/src/CallRerouting.php:358
./vendor/antecedent/patchwork/src/CallRerouting.php:436
./vendor/antecedent/patchwork/src/CallRerouting.php:291
./vendor/antecedent/patchwork/src/CallRerouting.php:468
./vendor/antecedent/patchwork/src/CallRerouting.php:233
./vendor/antecedent/patchwork/src/CallRerouting.php:255
./vendor/antecedent/patchwork/src/Stack.php:27
./vendor/antecedent/patchwork/src/CallRerouting.php:266
./vendor/sirbrillig/spies/src/Spies/GlobalSpies.php:109
./vendor/sirbrillig/spies/src/Spies/Spy.php:396
./vendor/sirbrillig/spies/src/Spies/Spy.php:124
./vendor/sirbrillig/spies/src/Spies/GlobalSpies.php:60
./vendor/sirbrillig/spies/src/Spies/GlobalSpies.php:120
./vendor/antecedent/patchwork/src/CallRerouting.php:233
./vendor/antecedent/patchwork/src/CallRerouting.php:255
./vendor/antecedent/patchwork/src/Stack.php:27
./vendor/antecedent/patchwork/src/CallRerouting.php:266
./func.php:4
./func-test.php:10
```

### Notes

* Using `\Patchwork\redefine( 'trigger_error', \Patchwork\always( null ) )` works fine.
* Redefine our own defined functions (e.g. `A`) with `\Spies\mock_function( 'A' )` works fine.

**Comment by sirbrillig** [comment]
Thank you for the report! This is a very interesting bug. I discovered that if you change the mock to return something other than `null`, the test will pass:

```php
\Spies\mock_function( 'trigger_error' )->and_return( 'foo' );
```

I think the issue is that it's difficult to determine if I have set a return value if the return value set is `null`, and so the Spy attempts to call the original method in [get_return_for](https://github.com/sirbrillig/spies/blob/master/src/Spies/Spy.php#L391-L397) or [replace_global_function](https://github.com/sirbrillig/spies/blob/master/src/Spies/GlobalSpies.php?utf8=%E2%9C%93#L121-L124).

I think I need to add a special case for returning `null` in mocked functions.

**Comment by sirbrillig** [comment]
Try 1.6. That should take care of this!
